CREATE TABLE IF NOT EXISTS currency (
    id BIGINT NOT NULL PRIMARY KEY,
    valute_id VARCHAR(255),
    num_code VARCHAR(255),
    char_code VARCHAR(255),
    nominal VARCHAR(255),
    name VARCHAR(255),
    value DOUBLE PRECISION,
    date DATE NOT NULL DEFAULT current_date
);

ALTER TABLE currency ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME currency_id_seq
        START WITH 1
        INCREMENT BY 1
);

CREATE TABLE IF NOT EXISTS history_convert (
    id BIGINT NOT NULL PRIMARY KEY,
    from_currency VARCHAR(255),
    to_currency VARCHAR(255),
    from_amount DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    date DATE NOT NULL DEFAULT current_date,
    user_id BIGINT NOT NULL
);

ALTER TABLE history_convert ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME history_convert_id_seq
        START WITH 1
        INCREMENT BY 1
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    password VARCHAR(255)
);

ALTER TABLE users ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME users_id_seq
        START WITH 1
        INCREMENT BY 1
        );


CREATE TABLE IF NOT EXISTS user_role (
    user_id BIGINT NOT NULL,
    role VARCHAR NOT NULL
);

INSERT INTO user_role (role, user_id)
VALUES ('USER', 1),
       ('USER', 2);

INSERT INTO users (name, password)
VALUES ('user', '$2a$10$ZEDaMWQ4L48kVxozylGM4O4DFeVTIX6dpT0DG3xb8C.syJSKbC7.O'),
       ('admin', '$2a$10$ZEDaMWQ4L48kVxozylGM4O4DFeVTIX6dpT0DG3xb8C.syJSKbC7.O');

INSERT INTO history_convert (from_currency, to_currency, from_amount, total_amount, date, user_id)
VALUES ('EUR (Евро)','RUB (Российский рубль)','3','265.3','2021-03-21','1'),
('EUR (Евро)','RUB (Российский рубль)','5','442.165','2021-03-21','1'),
('EUR (Евро)','RUB (Российский рубль)','1','88.433','2021-03-21','1'),
('USD (Доллар США)','RUB (Российский рубль)','5','370.695','2021-03-21','1'),
('EUR (Евро)','RUB (Российский рубль)','1','88.433','2021-03-21','1'),
('USD (Доллар США)','RUB (Российский рубль)','10','741.39','2021-03-21','1'),
('USD (Доллар США)','RUB (Российский рубль)','5','370.695','2021-03-21','1'),
('EUR (Евро)','RUB (Российский рубль)','3','265.3','2021-03-21','1'),
('EUR (Евро)','RUB (Российский рубль)','3','265.3','2021-03-21','1'),
('USD (Доллар США)','EUR (Евро)','3','2.515','2021-03-21','1'),
('ZAR (Южноафриканских рэндов)','CHF (Швейцарский франк)','10','6.317','2021-03-21','1'),
('RUB (Российский рубль)','USD (Доллар США)','148.278','2','2021-03-20','2'),
('USD (Доллар США)','RUB (Российский рубль)','2','148.278','2021-03-21','2'),
('USD (Доллар США)','RUB (Российский рубль)','1','74.139','2021-03-22','1'),
('NOK (Норвежских крон)','BRL (Бразильский реал)','1','6.55','2021-03-22','1');
